apiVersion: apps/v1
kind: Deployment
metadata:
  name: task
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task
  template:
    metadata:
      labels:
        app: task
    spec:
      containers:
        - name: task
          image: crpi-llc1n4kse5p1shit.cn-shenzhen.personal.cr.aliyuncs.com/micro-service1/micro-service:task
          ports:
            - containerPort: 10002
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
      volumes:
        - name: config-volume
          configMap:
            name: task-config
---
apiVersion: v1
kind: Service
metadata:
  name: task-service
spec:
  selector:
    app: task
  ports:
    - port: 10002
      targetPort: 10002
