// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/user/login": {
            "post": {
                "description": "处理用户登录请求，验证用户凭据并返回用户详细信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "用户登录请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.UserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回用户详细信息",
                        "schema": {
                            "$ref": "#/definitions/service.UserDetailResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/service.UserDetailResponse"
                        }
                    },
                    "401": {
                        "description": "用户验证失败",
                        "schema": {
                            "$ref": "#/definitions/service.UserDetailResponse"
                        }
                    }
                }
            }
        },
        "/user/register": {
            "post": {
                "description": "创建新用户账户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "description": "用户注册请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.UserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "注册成功返回用户信息",
                        "schema": {
                            "$ref": "#/definitions/service.UserDetailResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/service.UserDetailResponse"
                        }
                    },
                    "409": {
                        "description": "用户已存在",
                        "schema": {
                            "$ref": "#/definitions/service.UserDetailResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "service.UserDetailResponse": {
            "type": "object",
            "properties": {
                "Code": {
                    "type": "integer"
                },
                "UserDetail": {
                    "$ref": "#/definitions/service.UserModel"
                }
            }
        },
        "service.UserModel": {
            "type": "object",
            "properties": {
                "NickName": {
                    "description": "@inject_tag: json:\"nick_name\"",
                    "type": "string"
                },
                "UserID": {
                    "description": "@inject_tag: json:\"user_id\"",
                    "type": "integer"
                },
                "UserName": {
                    "description": "@inject_tag: json:\"user_name\"",
                    "type": "string"
                }
            }
        },
        "service.UserRequest": {
            "type": "object",
            "properties": {
                "NickName": {
                    "description": "inject_tag: json:\"nick_name\" form:\"nick_name\" uri:\"nick_name\"",
                    "type": "string"
                },
                "Password": {
                    "description": "inject_tag: json:\"password\" form:\"password\" uri:\"password\"",
                    "type": "string"
                },
                "PasswordConfirm": {
                    "description": "inject_tag: json:\"password_confirm\" form:\"password_confirm\" uri:\"password_confirm\"",
                    "type": "string"
                },
                "UserName": {
                    "description": "inject_tag: json:\"user_name\" form:\"user_name\" uri:\"user_name\"",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8001",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "User Service API",
	Description:      "User service for task management system",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
