// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: taskService.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskID        uint32                 `protobuf:"varint,1,opt,name=TaskID,proto3" json:"TaskID,omitempty"`
	UserID        uint32                 `protobuf:"varint,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Status        uint32                 `protobuf:"varint,3,opt,name=Status,proto3" json:"Status,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=Title,proto3" json:"Title,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=Content,proto3" json:"Content,omitempty"`
	StartTime     uint32                 `protobuf:"varint,6,opt,name=StartTime,proto3" json:"StartTime,omitempty"`
	EndTime       uint32                 `protobuf:"varint,7,opt,name=EndTime,proto3" json:"EndTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	mi := &file_taskService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taskService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_taskService_proto_rawDescGZIP(), []int{0}
}

func (x *TaskRequest) GetTaskID() uint32 {
	if x != nil {
		return x.TaskID
	}
	return 0
}

func (x *TaskRequest) GetUserID() uint32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *TaskRequest) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *TaskRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TaskRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *TaskRequest) GetStartTime() uint32 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *TaskRequest) GetEndTime() uint32 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

type TaskDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskDetail    []*TaskModel           `protobuf:"bytes,1,rep,name=TaskDetail,proto3" json:"TaskDetail,omitempty"`
	Code          uint32                 `protobuf:"varint,2,opt,name=Code,proto3" json:"Code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskDetailResponse) Reset() {
	*x = TaskDetailResponse{}
	mi := &file_taskService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskDetailResponse) ProtoMessage() {}

func (x *TaskDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_taskService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskDetailResponse.ProtoReflect.Descriptor instead.
func (*TaskDetailResponse) Descriptor() ([]byte, []int) {
	return file_taskService_proto_rawDescGZIP(), []int{1}
}

func (x *TaskDetailResponse) GetTaskDetail() []*TaskModel {
	if x != nil {
		return x.TaskDetail
	}
	return nil
}

func (x *TaskDetailResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type CommonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonResponse) Reset() {
	*x = CommonResponse{}
	mi := &file_taskService_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonResponse) ProtoMessage() {}

func (x *CommonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_taskService_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonResponse.ProtoReflect.Descriptor instead.
func (*CommonResponse) Descriptor() ([]byte, []int) {
	return file_taskService_proto_rawDescGZIP(), []int{2}
}

func (x *CommonResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CommonResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *CommonResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_taskService_proto protoreflect.FileDescriptor

const file_taskService_proto_rawDesc = "" +
	"\n" +
	"\x11taskService.proto\x12\x02pb\x1a\x10taskModels.proto\"\xbd\x01\n" +
	"\vTaskRequest\x12\x16\n" +
	"\x06TaskID\x18\x01 \x01(\rR\x06TaskID\x12\x16\n" +
	"\x06UserID\x18\x02 \x01(\rR\x06UserID\x12\x16\n" +
	"\x06Status\x18\x03 \x01(\rR\x06Status\x12\x14\n" +
	"\x05Title\x18\x04 \x01(\tR\x05Title\x12\x18\n" +
	"\aContent\x18\x05 \x01(\tR\aContent\x12\x1c\n" +
	"\tStartTime\x18\x06 \x01(\rR\tStartTime\x12\x18\n" +
	"\aEndTime\x18\a \x01(\rR\aEndTime\"W\n" +
	"\x12TaskDetailResponse\x12-\n" +
	"\n" +
	"TaskDetail\x18\x01 \x03(\v2\r.pb.TaskModelR\n" +
	"TaskDetail\x12\x12\n" +
	"\x04Code\x18\x02 \x01(\rR\x04Code\"J\n" +
	"\x0eCommonResponse\x12\x12\n" +
	"\x04Code\x18\x01 \x01(\rR\x04Code\x12\x10\n" +
	"\x03Msg\x18\x02 \x01(\tR\x03Msg\x12\x12\n" +
	"\x04Data\x18\x03 \x01(\tR\x04Data2\xdb\x01\n" +
	"\vTaskService\x121\n" +
	"\n" +
	"TaskCreate\x12\x0f.pb.TaskRequest\x1a\x12.pb.CommonResponse\x121\n" +
	"\n" +
	"TaskUpdate\x12\x0f.pb.TaskRequest\x1a\x12.pb.CommonResponse\x123\n" +
	"\bTaskShow\x12\x0f.pb.TaskRequest\x1a\x16.pb.TaskDetailResponse\x121\n" +
	"\n" +
	"TaskDelete\x12\x0f.pb.TaskRequest\x1a\x12.pb.CommonResponseB\x1bZ\x19/internal/service;serviceb\x06proto3"

var (
	file_taskService_proto_rawDescOnce sync.Once
	file_taskService_proto_rawDescData []byte
)

func file_taskService_proto_rawDescGZIP() []byte {
	file_taskService_proto_rawDescOnce.Do(func() {
		file_taskService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_taskService_proto_rawDesc), len(file_taskService_proto_rawDesc)))
	})
	return file_taskService_proto_rawDescData
}

var file_taskService_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_taskService_proto_goTypes = []any{
	(*TaskRequest)(nil),        // 0: pb.TaskRequest
	(*TaskDetailResponse)(nil), // 1: pb.TaskDetailResponse
	(*CommonResponse)(nil),     // 2: pb.CommonResponse
	(*TaskModel)(nil),          // 3: pb.TaskModel
}
var file_taskService_proto_depIdxs = []int32{
	3, // 0: pb.TaskDetailResponse.TaskDetail:type_name -> pb.TaskModel
	0, // 1: pb.TaskService.TaskCreate:input_type -> pb.TaskRequest
	0, // 2: pb.TaskService.TaskUpdate:input_type -> pb.TaskRequest
	0, // 3: pb.TaskService.TaskShow:input_type -> pb.TaskRequest
	0, // 4: pb.TaskService.TaskDelete:input_type -> pb.TaskRequest
	2, // 5: pb.TaskService.TaskCreate:output_type -> pb.CommonResponse
	2, // 6: pb.TaskService.TaskUpdate:output_type -> pb.CommonResponse
	1, // 7: pb.TaskService.TaskShow:output_type -> pb.TaskDetailResponse
	2, // 8: pb.TaskService.TaskDelete:output_type -> pb.CommonResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_taskService_proto_init() }
func file_taskService_proto_init() {
	if File_taskService_proto != nil {
		return
	}
	file_taskModels_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_taskService_proto_rawDesc), len(file_taskService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_taskService_proto_goTypes,
		DependencyIndexes: file_taskService_proto_depIdxs,
		MessageInfos:      file_taskService_proto_msgTypes,
	}.Build()
	File_taskService_proto = out.File
	file_taskService_proto_goTypes = nil
	file_taskService_proto_depIdxs = nil
}
