// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: taskModels.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskModel struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"favorite_id"
	TaskID uint32 `protobuf:"varint,1,opt,name=TaskID,proto3" json:"TaskID,omitempty"`
	// @inject_tag: json:"user_id"
	UserID uint32 `protobuf:"varint,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	// @inject_tag: json:"status"
	Status uint32 `protobuf:"varint,3,opt,name=Status,proto3" json:"Status,omitempty"`
	// @inject_tag: json:"title"
	Title string `protobuf:"bytes,4,opt,name=Title,proto3" json:"Title,omitempty"`
	// @inject_tag: json:"content"
	Content string `protobuf:"bytes,5,opt,name=Content,proto3" json:"Content,omitempty"`
	// @inject_tag: json:"start_time"
	StartTime uint32 `protobuf:"varint,6,opt,name=StartTime,proto3" json:"StartTime,omitempty"`
	// @inject_tag: json:"end_time"
	EndTime       uint32 `protobuf:"varint,7,opt,name=EndTime,proto3" json:"EndTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskModel) Reset() {
	*x = TaskModel{}
	mi := &file_taskModels_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskModel) ProtoMessage() {}

func (x *TaskModel) ProtoReflect() protoreflect.Message {
	mi := &file_taskModels_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskModel.ProtoReflect.Descriptor instead.
func (*TaskModel) Descriptor() ([]byte, []int) {
	return file_taskModels_proto_rawDescGZIP(), []int{0}
}

func (x *TaskModel) GetTaskID() uint32 {
	if x != nil {
		return x.TaskID
	}
	return 0
}

func (x *TaskModel) GetUserID() uint32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *TaskModel) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *TaskModel) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TaskModel) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *TaskModel) GetStartTime() uint32 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *TaskModel) GetEndTime() uint32 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

var File_taskModels_proto protoreflect.FileDescriptor

const file_taskModels_proto_rawDesc = "" +
	"\n" +
	"\x10taskModels.proto\x12\x02pb\"\xbb\x01\n" +
	"\tTaskModel\x12\x16\n" +
	"\x06TaskID\x18\x01 \x01(\rR\x06TaskID\x12\x16\n" +
	"\x06UserID\x18\x02 \x01(\rR\x06UserID\x12\x16\n" +
	"\x06Status\x18\x03 \x01(\rR\x06Status\x12\x14\n" +
	"\x05Title\x18\x04 \x01(\tR\x05Title\x12\x18\n" +
	"\aContent\x18\x05 \x01(\tR\aContent\x12\x1c\n" +
	"\tStartTime\x18\x06 \x01(\rR\tStartTime\x12\x18\n" +
	"\aEndTime\x18\a \x01(\rR\aEndTimeB\x1bZ\x19/internal/service;serviceb\x06proto3"

var (
	file_taskModels_proto_rawDescOnce sync.Once
	file_taskModels_proto_rawDescData []byte
)

func file_taskModels_proto_rawDescGZIP() []byte {
	file_taskModels_proto_rawDescOnce.Do(func() {
		file_taskModels_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_taskModels_proto_rawDesc), len(file_taskModels_proto_rawDesc)))
	})
	return file_taskModels_proto_rawDescData
}

var file_taskModels_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_taskModels_proto_goTypes = []any{
	(*TaskModel)(nil), // 0: pb.TaskModel
}
var file_taskModels_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_taskModels_proto_init() }
func file_taskModels_proto_init() {
	if File_taskModels_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_taskModels_proto_rawDesc), len(file_taskModels_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_taskModels_proto_goTypes,
		DependencyIndexes: file_taskModels_proto_depIdxs,
		MessageInfos:      file_taskModels_proto_msgTypes,
	}.Build()
	File_taskModels_proto = out.File
	file_taskModels_proto_goTypes = nil
	file_taskModels_proto_depIdxs = nil
}
